#!/bin/sh /etc/rc.common
EXTRA_COMMANDS="backup reset status upgrade alias"
EXTRA_HELP="        backup  	Create ram-root backup
        reset   	Reset backup of ram-root
        status  	Show ram-root status
        upgrade 	Run 'opkg upgrade' command"

START=99
STOP=33

start() {
	/ram-root/ram-root.sh start
	exit $?
}

stop() {
	/ram-root/ram-root.sh stop
	exit $?
}

restart() {
	stop
}

reload () {
	stop
}

backup() {
	/ram-root/ram-root.sh backup
	exit $?
}

reset() {
	/ram-root/ram-root.sh reset
	exit $?
}

status() {
	[ -e /tmp/ram-root-active ] && echo -e "\arunning" || echo -e "\aNOT running"
	exit 0
}

upgrade() {
	/ram-root/ram-root.sh upgrade
	exit $?
}
